name: Forge Fork Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

jobs:
  check:
    name: Fork Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: |
          forge --version
          make sizes
        id: build

      - name: Run Forge fork tests
        env:
          MNEMONIC: ${{ secrets.MNEMONIC_FOR_TESTS }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
        run: make fork profile=ci
        id: fork
